# Generated by Django 5.0.4 on 2024-08-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_featuredcategory_product_featured_category'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featuredcategory',
            options={'verbose_name': 'Featured Category', 'verbose_name_plural': 'Featured Categories'},
        ),
        migrations.AddField(
            model_name='featuredcategory',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True, verbose_name='Featured Category Safe URL'),
            preserve_default=False,
        ),
    ]
