# Generated by Django 5.0.4 on 2024-08-28 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_featuredcategory_options_featuredcategory_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Category Safe URL'),
        ),
    ]
