# Generated by Django 5.0.4 on 2024-08-28 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuredcategory',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True, verbose_name='Featured Category Safe URL'),
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(editable=False, max_length=255, unique=True),
        ),
    ]
