# Generated by Django 5.0.4 on 2024-09-03 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_featuredcategory_slug_alter_product_slug'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImages',
            new_name='ProductImage',
        ),
    ]
