# Generated by Django 5.0.4 on 2024-09-03 20:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_productimages_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='item',
        ),
        migrations.AddField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='store.product'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(help_text='Description of the image for SEO purposes', max_length=255, verbose_name='Alternative text'),
        ),
    ]
