# Generated by Django 5.0.4 on 2024-09-03 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_productimage_item_productimage_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='alt_text',
            field=models.CharField(default='product image', help_text='Description of the image for SEO purposes', max_length=255, verbose_name='Alternative text'),
        ),
    ]
