# Generated by Django 5.0.4 on 2024-09-07 10:30

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("store", "Category")
    for row in MyModel.objects.all():
        row.category_id = uuid.uuid4()
        row.save(update_fields=["category_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_remove_category_slug_category_category_id_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
