# Generated by Django 5.0.4 on 2024-09-07 11:45

import abstract.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('store', '0013_remove_productimage_product_category_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorymedia',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='contenttypes.contenttype'),
        ),
        migrations.CreateModel(
            name='ProductMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('image', models.ImageField(upload_to=abstract.models.AbstractMediaModel.directory_path, verbose_name='image')),
                ('alt_text', models.CharField(default='this is image', help_text='Description of the image for SEO purposes', max_length=255, verbose_name='Alternative text')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='%(class)s', to='contenttypes.contenttype')),
            ],
            options={
                'verbose_name': 'Product Image',
                'verbose_name_plural': 'Product Images',
            },
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
