# Generated by Django 5.0.4 on 2024-09-07 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_categorymedia_content_type_productmedia_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='name',
            new_name='title',
        ),
    ]
