# Generated by Django 5.0.4 on 2025-02-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_fix_weight_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='manufacturing_cost',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 99999999.99.'}}, help_text='Maximum 99999999.99', max_digits=10, null=True, verbose_name='Manufacturing Cost'),
        ),
        migrations.AddField(
            model_name='product',
            name='retail_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 99999999.99.'}}, help_text='Maximum 99999999.99', max_digits=10, null=True, verbose_name='Retail Price'),
        ),
        migrations.AddField(
            model_name='product',
            name='whole_sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 99999999.99.'}}, help_text='Maximum 99999999.99', max_digits=10, null=True, verbose_name='Whole Sale Price'),
        ),
    ]
