# Generated by Django 5.0.4 on 2025-02-14 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_product_manufacturing_cost_product_retail_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='retail_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='whole_sale_price',
        ),
    ]
