services:
  backend:
    build: ./backend
    ports:
      - "8002:8002"
    volumes:
      - ./backend:/app
    environment:
      - DEBUG=True
      - DJANGO_ALLOWED_HOSTS=backend,localhost,127.0.0.1
      - DATABASE_URL=postgres://postgres:postgres@db:5432/seo_db
    depends_on:
      - db

  db:
    image: postgres:17.3
    container_name: zubies_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=zubies_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5435:5432"

volumes:
  postgres_data: 