# Generated by Django 5.0.4 on 2024-06-11 19:15

import django.db.models.deletion
import django_countries.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last Name')),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone Number')),
                ('address_line_1', models.CharField(max_length=150, verbose_name='Address Line 1')),
                ('address_line_2', models.CharField(blank=True, max_length=150, verbose_name='Address Line 2')),
                ('city', models.CharField(max_length=150, verbose_name='City')),
                ('state', models.CharField(max_length=150, verbose_name='State/Province/Region')),
                ('country', django_countries.fields.CountryField(max_length=2, verbose_name='Country')),
                ('zip_code', models.CharField(max_length=12, verbose_name='Zip Code')),
                ('default', models.BooleanField(default=False, verbose_name='Default')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Customer')),
            ],
            options={
                'verbose_name': 'Billing Address',
                'verbose_name_plural': 'Billing Addresses',
            },
        ),
    ]
