# Generated by Django 5.0.4 on 2024-09-01 20:29

import django_countries.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(choices=[('', 'City'), ('abd', 'Attock'), ('abt', 'Abbottabad'), ('bhr', 'Bahawalnagar'), ('bwn', 'Bhawana'), ('bhk', 'Bhakkar'), ('bwp', 'Bahawalpur'), ('cwp', 'Chishtian'), ('dgh', 'Dera Ghazi Khan'), ('dnb', 'Dinawali'), ('dip', 'Dipalpur'), ('fdr', 'Fateh Jhang'), ('fsl', 'Faisalabad'), ('ghk', 'Gujar Khan'), ('gjr', 'Gujranwala'), ('grk', 'Gwadar'), ('grw', 'Gujranwala'), ('gjr', 'Gujrat'), ('hyd', 'Hyderabad'), ('isl', 'Islamabad'), ('jlm', 'Jalalpur'), ('jwn', 'Jaranwala'), ('jwp', 'Jhelum'), ('khr', 'Khairpur'), ('khi', 'Karachi'), ('khr', 'Khanewal'), ('ktt', 'Kotli'), ('kwb', 'Kot Adu'), ('lai', 'Lalamusa'), ('lhr', 'Lahore'), ('ldr', 'Lodhran'), ('lrd', 'Larkana'), ('ltr', 'Layyah'), ('mll', 'Mian Channu'), ('mlk', 'Malakwal'), ('mlt', 'Mardan'), ('mrd', 'Multan'), ('mnt', 'Mansehra'), ('mgw', 'Mandi Bahauddin'), ('mwm', 'Mianwali'), ('mtr', 'Multan'), ('mzt', 'Murree'), ('mzw', 'Muzaffargarh'), ('ngt', 'Narowal'), ('nwn', 'Nankana Sahib'), ('pwp', 'Peshawar'), ('phl', 'Pattoki'), ('qta', 'Quetta'), ('qrb', 'Quetta Residency'), ('rch', 'Rajanpur'), ('rnw', 'Rawalpindi'), ('rkn', 'Rahim Yar Khan'), ('rwp', 'Rawalpindi'), ('sgr', 'Sargodha'), ('skt', 'Sialkot'), ('shw', 'Sheikhupura'), ('swn', 'Swat'), ('sak', 'Sargodha'), ('sbq', 'Sahiwal'), ('ska', 'Sakrand'), ('skz', 'Sukheki'), ('stw', 'Sialkot'), ('suk', 'Sukkur'), ('swl', 'Sahiwal'), ('sgr', 'Sargodha'), ('swl', 'Sialkot'), ('saw', 'Sawat'), ('ttn', 'Toba Tek Singh'), ('vhn', 'Vehari'), ('wah', 'Wah Cantt'), ('wln', 'Wazirabad')], max_length=150, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='country',
            field=django_countries.fields.CountryField(default='PK', max_length=2, verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='state',
            field=models.CharField(max_length=150, verbose_name='State/Province'),
        ),
    ]
