# Generated by Django 5.0.4 on 2024-06-11 15:02

import django.db.models.deletion
import more.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BecomeSeller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=255, verbose_name='Brand Name')),
                ('authorized_person_name', models.CharField(max_length=255, verbose_name='Authorized Person Name')),
                ('authorized_person_email', models.CharField(max_length=255, verbose_name='Authorized Person Email')),
                ('authorized_person_tel', models.CharField(max_length=255, verbose_name='Authorized Person Contact Phone/Mobile Number')),
                ('city', models.CharField(help_text='In which city does the Brand proudly conduct its operations?', max_length=150, verbose_name='City')),
                ('website', models.URLField(blank=True, max_length=255, verbose_name='Do you have any Website?')),
                ('products_category', models.CharField(choices=[('KDS', 'Kids'), ('MR', 'Manufacturer'), ('MN', 'Men'), ('SME', 'SME'), ('WMN', 'Women')], max_length=12, verbose_name='Products Category')),
                ('catalogue_size', models.CharField(choices=[('1', '1-9'), ('2', '10-19'), ('3', '20-49'), ('4', '50-99'), ('5', '100-199'), ('6', '200+')], help_text='Number of products that you sell', max_length=12, verbose_name='Catalogue Size')),
                ('retail_price', models.DecimalField(decimal_places=2, error_messages={'name': {'max_length': 'The price must be between 0 and 99999999.99.'}}, help_text='Maximum 99999999.99', max_digits=10, verbose_name='Retail Price')),
                ('supply_chain', models.CharField(choices=[('IH', 'In-House (Self Production)'), ('O', 'Outsourced')], help_text='Inhouse: Select this if you own machines/setup\nOutsourced: Select this if you do not own machines/setup and buy services from 3rd party vendors. ', max_length=12, verbose_name='How do you manage your Supply Chain?')),
                ('inventory', models.CharField(choices=[('YES', 'Yes, Ready to Ship'), ('NO', 'No, Made to Order'), ('BTH', 'Both')], max_length=12, verbose_name='Do you produce inventory before selling?')),
                ('feedback', models.TextField(help_text='Please give a brief introduction of your company', verbose_name='If any, please share your feedback regarding the form.')),
                ('time_created', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Become Seller',
                'verbose_name_plural': 'Become Seller List',
                'ordering': ('-time_created',),
            },
        ),
        migrations.CreateModel(
            name='BusinessOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='NewsLetter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='BecomeSellerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=more.models.BecomeSellerImage.user_directory_path, verbose_name='image')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='img', to='more.becomeseller')),
            ],
            options={
                'verbose_name': 'Become Seller Product Image',
                'verbose_name_plural': 'Become Seller Product Images',
            },
        ),
        migrations.AddField(
            model_name='becomeseller',
            name='bussiness_operations',
            field=models.ManyToManyField(help_text='If applicable, you may select multiple options', max_length=12, to='more.businessoperation', verbose_name="Brand's Business Operations"),
        ),
    ]
