# Generated by Django 5.0.4 on 2024-11-23 20:38

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('more', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newsletter',
            options={'ordering': ['-created_at'], 'verbose_name': 'Newsletter Subscription', 'verbose_name_plural': 'Newsletter Subscriptions'},
        ),
        migrations.AddField(
            model_name='newsletter',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newsletter',
            name='subscribed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='newsletter',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newsletter',
            name='email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator()]),
        ),
    ]
