# Generated by Django 4.1.5 on 2023-07-11 11:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("more", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="becomesellerimage",
            options={
                "verbose_name": "Become Seller Product Image",
                "verbose_name_plural": "Become Seller Product Images",
            },
        ),
    ]
